name: web_view_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  dio: ^4.0.0
  data_connection_checker: ^0.3.4
  flutter_screenutil: ^3.2.0
  font_awesome_flutter: ^9.1.0
  flutter_svg:
  fluttertoast: ^8.0.7
  auto_size_text: ^2.1.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/lang/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

    - family: SF
      fonts:
        - asset: assets/fonts/sf_font.ttf
